# template, populated by script
interface=@WIFI_IFACE@
bridge=@BRIDGE_IFACE@
driver=nl80211
ssid=@SSID@
hw_mode=g
channel=6
wpa=2
wpa_passphrase=@WPA_PASSPHRASE@
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP

# Client isolation
ap_isolate=1
