table bridge filter {
	chain forward {
		type filter hook forward priority 0; policy drop;
		
		# Redundant with hostapd's ap_isolate but provides defence in depth for
		# no station-to-station traffic
		iifname "@WIFI_IFACE@" oifname "@WIFI_IFACE@" drop

		# Allow Wi-Fi clients to uplink
		iifname "@WIFI_IFACE@" oifname "@UPLINK_IFACE@" accept

		# Allow return traffic
		iifname "@UPLINK_IFACE@" oifname "@WIFI_IFACE@" accept
	}
}
