#!/usr/bin/env python3
"""
Computes SHA-256 of a built application firmware binary and writes it as a
C++ header for the provisioning formware to embed.

Run AFTER building the application firmware, and BEFORE building the
provisioning firmware.

Usage:
    python3 compute_firmware_hash.py \
        --bin apps/device-main/build/device-main.bin \
        --out components/provisioning/include/firmware_hash.hpp
"""
import argparse
import hashlib
from pathlib import Path

TEMPLATE = """\
// AUTO-GENERATED by compute_firmware_hash.py - DO NOT EDIT.
// SHA-256 of: {bin_path}
// Computed:   {timestamp}
#pragma once

inline constexpr const char* FIRMWARE_SHA256_HEX = {hash_hex}";
"""


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--bin", required=True,
                   help="Path to the built application .bin")
    p.add_argument("--out", required=True,
                   help="Output header path")
    args = p.parse_args()

    bin_path = Path(args.bin)
    if not bin_path.exists():
        raise SystemExit(
            f"ERROR: {bin_path} does not exist - build the application "
            "firmware first (idf.py build in apps/device-main)")

    digest = hashlib.sha256(bin_path.read_bytes()).hexdigest()

    import datetime
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(TEMPLATE.format(
        bin_path=bin_path,
        timestamp=datetime.datetime.now(datetime.timezone.utc).isoformat(),
        hash_hex=digest,
    ))

    print(f"SHA-256: {digest}")
    print(f"Wrote:   {out_path}")


if __name__ == "__main__":
    main()
