// AUTO-GENERATED by compute_firmware_hash.py - DO NOT EDIT.
// SHA-256 of: apps/device-main/build/device-main.bin
// Computed:   2026-09-27T14:18:41.948738+00:00
#pragma once

inline constexpr const char* FIRMWARE_SHA256_HEX = "d89ee89c7608f846fe95c0cae857156dd5aa55c8939129cb95453731d90dd72b";
